language: node_js
node_js:
  - "node"
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master